### ISSUE TITLE
Cannot get cnspec provisioner to fail under any circumstances

### ISSUE THREAD

**Issue by drewmullen** [mondoohq/packer-plugin-cnspec#100] opened 2023-04-10 18:39 UTC
**Describe the bug**
As I test this tool I'm trying to get it to fail on any check and validate the image is not published. Looking through the source code it seems like you only check for `on_failure` to be [`continue` or not](https://github.com/mondoohq/packer-plugin-cnspec/blob/main/provisioner/provisioner.go#L589-L595). Setting `on_failure` to anything else doesnt seem to fail the build under any combinations i have tried...

This tool is new to me so its possible I'm missing something easy

Example of a few checks that are failing in my test:

```
    azure-arm.centos: ✕ Fail:  F   0  Ensure source routed packets are not accepted
    azure-arm.centos: ! Error: Ensure SSH X11 forwarding is disabled
    azure-arm.centos: ✓ Pass:  A 100  Ensure NIS server is stopped and not enabled
    azure-arm.centos: ✕ Fail:  D  20  Ensure session initiation information is collected
```

Combinations I've tried:

```
  provisioner "cnspec" {
    on_failure      = "fail"
    score_threshold = 1
  }
```

```
  provisioner "cnspec" {
    on_failure      = "fail"
    score_threshold = 100
  }
```

**Expected behavior**
Packer provisioner `cnspec` should fail, the build should fail, then clean up resources - not publishing any image

However, I'm still getting images published: 
<img width="542" alt="image" src="https://user-images.githubusercontent.com/3812162/230970025-7d4a1d02-fb4c-4329-a8d1-b339d8531c33.png">

**Comment by drewmullen** [comment] 2023-04-10 18:40
also, id just like to apologize for opening so many issues in such a short time 😅

@chris-rock

**Comment by tas50** [comment] 2023-04-10 18:41
@drewmullen keep them coming!

**Comment by chris-rock** [comment] 2023-04-14 20:55
I tried

```
  provisioner "cnspec" {
    on_failure =  "fail"
    policybundle = "custom-policy.mql.yaml" 
    score_threshold = 60
  }
```

And I see the build fail, the score threshold is also respected

<img width="947" alt="Screenshot 2023-04-14 at 22 53 03" src="https://user-images.githubusercontent.com/1178413/232152543-6cd4208a-4de0-46c2-af51-718a66c8255e.png">

When I change the config to:

```
provisioner "cnspec" {
    on_failure =  "fail"
    policybundle = "custom-policy.mql.yaml" 
    score_threshold = 40
}
```

the run passes as expected

<img width="989" alt="Screenshot 2023-04-14 at 22 55 05" src="https://user-images.githubusercontent.com/1178413/232152863-21a814e7-a20c-4633-9e34-eb9cd75b44bc.png">

So far, I am not able to reproduce the issue.

**Comment by drewmullen** [comment] 2023-04-17 15:36
ack - gimme a day or so and ill get back to you

**Comment by drewmullen** [comment] 2023-04-17 18:27
alright i guess im looking for ideas from you on what i can try. heres an example of some failures, i tried to show 1 on both sides of the threshold i set:

```
    azure-arm.centos: ✕ Fail:  C  40  Ensure system is disabled when audit logs are full
    azure-arm.centos: ! Error: Ensure only strong ciphers are used
    azure-arm.centos: ✕ Fail:  D  20  Ensure events that modify user/group information are colle...
```

My provisioner settings:

```
  provisioner "cnspec" {
    on_failure = "fail"
    score_threshold = 35
  }
```

I noticed that my output doesnt have the `Controls: {Pass,Fail}` section at the end like yours does. You can see that the checks just end and then the packer build continues

<img width="841" alt="image" src="https://user-images.githubusercontent.com/3812162/232577921-0d8ea3cc-41fc-4e0a-8c72-1ba0b45e215c.png">

**Comment by chris-rock** [comment] 2024-01-27 16:53
I retested the issues again with the docker example:

```hcl
packer {
  required_plugins {
    docker = {
      version = ">= 0.0.7"
      source  = "github.com/hashicorp/docker"
    }
    cnspec = {
      version = ">= 10.0.0"
      source  = "github.com/mondoohq/cnspec"
    }
  }
}

variable "image_prefix" {
  type        = string
  description = "Prefix to be applied to image name"
  default     = "mondoo-ubuntu-2004-secure-base"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "docker" "ubuntu" {
  image  = "ubuntu:jammy"
  commit = true
}

build {
  name    = "mondoo-docker-ubuntu-2004-secure-base"
  sources = [
    "source.docker.ubuntu"
  ]

  provisioner "shell" {
    inline = [
      "echo \"${var.image_prefix}-${local.timestamp}\" > /etc/hostname",
    ]
  }

  provisioner "cnspec" {
    # on_failure  = "continue"
    asset_name  = "${var.image_prefix}-${local.timestamp}"
    score_threshold = 100
    annotations = {
      Name              = "${var.image_prefix}-${local.timestamp}"
      Description       = "Mondoo Secure Ubuntu 20.04 Base Image"
      # see https://developer.hashicorp.com/packer/docs/templates/hcl_templates/contextual-variables#build-variables
      Build             = "${ build.PackerRunUUID }"
      Source            = "${ source.name }"
      SourceImageDigest = "${ build.SourceImageDigest }"
    }
    output        = "junit"
    output_target = "test-results.xml"
  }
}
```

<img width="1624" alt="Screenshot 2024-01-27 at 17 52 30" src="https://github.com/mondoohq/packer-plugin-cnspec/assets/1178413/c22b1280-3486-4072-ba01-e31e38467390">

I get the correct result. 100 means all checks need to pass, 0 would mean no check needs to pass.

**Comment by chris-rock** [comment] 2024-01-30 12:40
Closing this for now since I am not able to reproduce. Please let us know if the issue still happens.

**Closed by chris-rock** 2024-01-30 12:40 UTC
